--- 
services: 
  db: 
    command: "--default-authentication-plugin=mysql_native_password"
    environment: 
      - MYSQL_ROOT_PASSWORD=wordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    expose: 
      - 3306
      - 33060
    image: "mysql:8.0.19"
    restart: always
    volumes: 
      - "db_data:/var/lib/mysql"
  wordpress: 
    environment: 
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    image: "wordpress:latest"
    ports: 
      - "80:80"
    restart: always
volumes: 
   db_data:
version: "3.7"
